#integers
a=10
print(a)
b=20
print(b)
print(type(b))
#boolean
phone=True
print(phone)
print(type(phone))
#float
x=3.14
print(x)
print(type(x))
#string
name="jyothika"
print(name)
print(type(name))
#list
numbers=[1,2,3,4,5]
print(numbers)
print(type(numbers))
#tuple
coordinates=(10,20)
print(coordinates)
print(type(coordinates))
#set
unique_numbers={1,2,3,4,5}
print(unique_numbers)
print(type(unique_numbers))
#dictionary
student={"name":"jyothika","age":17}
print(student)
print(type(student))